### ISSUE TITLE
Simultaneous requests to /api/flickr/most-recent-photos causes server to crash

### ISSUE THREAD

**Issue by ryanoshea** [ryanoshea/ryanoshea.com#31]
Can't reproduce locally, only on server.

Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at onwrite (_stream_writable.js:437:11)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:12)
    at Immediate._onImmediate (/home/ryan/ryanoshea.com/backend/node_modules/handle-thing/lib/handle.js:127:11)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_MULTIPLE_CALLBACK'
}

**Comment by ryanoshea** [comment]
This looks like an incompatibility issue with `spdy` on Node v12.

Investigation notes:

- Error originates in a dependency of `spdy`. There's also a deprecation message on Node v12 with the way this package modifies headers. Possible indication that `spdy@4.0.2` doesn't support Node v12.
- Reverting to flickrapi doesn't prevent the issue.
- Simplifying the request down to a single promise that does `res.send()` in its callback doesn't prevent the issue.
- Using `async/await` and moving the `res.send()` into the body of the request handler doesn't prevent the issue.
- Removing the async/promise behavior altogether from the request handler fixes the issue.
- Downgrading to Node v10 fixes the issue.
